site_name: pmsloths
extra_css: [style.css]
repo_url: https://github.com/pmsloths/home
linkedin_url: https://www.linkedin.com/in/tobetwobees2b
linkedin_connect_title: "Let's connect! üëã"
site_url: https://pmsloths.github.io/home/
site_description: pmsloths blog
site_author: pmsloths
use_directory_urls: true
nav:
  - Trang ch·ªß:
    - Index: index.md
  - Qu·∫£n l√Ω s·∫£n ph·∫©m:
      - Function as a Model VN: guide/function-classifier/function-classifier.md
      - Human Preprocessing VN: guide/function-preprocess/function-preprocessing.md
      - Drawing as a Model VN: guide/drawing-classifier/drawing.md
      - Outliers and Comfort VN: guide/finding-outliers/outliers.md
      - Drawing Features VN: guide/drawing-features/custom-features.md
  - Gi·∫£i quy·∫øt v·∫•n ƒë·ªÅ:
    - Models:
      - Classification: api/classification.md
      - Regression: api/regression.md
      - Outlier: api/outlier.md
      - Preprocessing: api/preprocessing.md
    - Interactive:
      - Charts: api/interactive-charts.md
    - Utility:
      - Common: api/common.md
      - Datasets: api/datasets.md
      - Rulers: api/rulers.md
  - T·ªânh th·ª©c:
    - Model Mining: examples/model-mining.md
    - S·ª≠ d·ª•ng: examples/usage.md
    - FAQ: examples/faq.md
plugins:
  - search
  - i18n:
      default_language: vi
      languages:
        vi: 
          name: Vi·ªát Nam
          site_name: Thinking fast and sloths ü¶•
        en: 
          name: English
          site_name: Thinking fast and sloths ü¶•
      nav_translations:
        en:
          Trang ch·ªß: Home
          Qu·∫£n l√Ω s·∫£n ph·∫©m: Product Management
          Function as a Model VN: Function as a Model EN
          Human Preprocessing VN: Human Preprocessing EN
          Drawing as a Model VN: Drawing as a Model EN
          Outliers and Comfort VN: Outliers and Comfort EN
          Drawing Features VN: Drawing Features EN
          Gi·∫£i quy·∫øt v·∫•n ƒë·ªÅ: Problem Solving
          Models: Models EN
          Classification: Classification EN
          T·ªânh th·ª©c: Mindfulness
          Model Mining: Model Mining EN
          S·ª≠ d·ª•ng: Usage
          FAQ: FAQ EN
copyright: Copyright &copy; 2022 PM Sloths
theme:
  name: material
  custom_dir: docs/theme/
  icon:
    logo: material/library
  font:
    text: Ubuntu
    code: Ubuntu Mono
  favicon: icon.png
  logo: icon.png
  features:
    - navigation.tabs
    # - toc.integrate
    # - toc.follow
    - navigation.top
  palette:
    primary: indigo
    accent: blue
markdown_extensions:
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      permalink: true